### PR TITLE
Add run_auto_mount()

### PR DESCRIPTION
**Pull request by joelnitta**
I had an idea to simplify mounting volumes. It can often be a pain to mentally map out how all the volumes should be mounted when running a command with multiple file inputs and outputs. This function abstracts that away so we can be closer to just running the command as if the software were installed locally.

This adds two zero-dependency packages to `Imports`, `fs` and `digest` (technically `glue` too, but that is a "freebie" since it's already imported by `dplyr`).

I have tested with docker but not singularity. I hope you will give it a try!

### CODE REVIEW

**Comment by rcannood** [comment]
Hey @joelnitta ! Thanks for creating this PR, I really appreciate your input.

I made a few changes. Could you take a look?

**Comment by joelnitta** [comment]
Thanks for taking a look at this @rcannood. I'm glad you agree it's useful!

That makes sense to me - no need to create a different directory in the container for each file if they already live in the same directory locally.

One thought I had after making the PR is that another option would actually be to modify `babelwhale::run()` instead adding a new function: basically, `babelwhale::run()` could have a new argument `auto_mount` that takes either `TRUE` or `FALSE`, and if `TRUE` does the automatic mounting (ignoring any input to `volumes`). This might make it a bit simpler for users since they wouldn't have to think about another function. I don't think such an approach would cause any backwards incompatibility if it were `FALSE` by default.

(oh wait, there's also the `wd_in_container` argument... so it would add two arguments. Anyways, please let me know which approach you think is better, or if you have another idea).

**Comment by rcannood** [comment]
I think it's better to keep it as a separate function, `run_auto_mount()`, because it better highlights the added functionality. If you look at the list of functions in `babelwhale` and you see a function called `run_auto_mount()`, you might be inclined to check out what it does :)

**Comment by rcannood** [comment]
@joelnitta Since this is already your second PR, and this one is new functionality that you developed, can I add you as an author to babelwhale?

**Comment by joelnitta** [comment]
I would be honored, thanks!

**Comment by rcannood** [comment]
babelwhale 1.1.0 is on CRAN! → https://cran.r-project.org/web/packages/babelwhale/index.html

**Pull request merged**
